{% set name = "bg-atlasapi" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/brainglobe/bg-atlasapi/archive/v{{ version }}.tar.gz
    sha256: 2e0d19bff54387262abc73055d7ba2e76495fe7dcb5a8ad277647cde93984af4
    folder: gh_archive
  # pypi source only added so the bot can detect new releases - installation uses the GH archive above
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bg-atlasapi-{{ version }}.tar.gz
    sha256: a52c5935975be8bce92f527f017a6222d891f3abc2161b4b82c9b2f6d2d880e7
    folder: pypi_tarball

build:
  entry_points:
    - brainglobe = bg_atlasapi.cli:bg_cli
  noarch: python
  script: {{ PYTHON }} -m pip install ./gh_archive/ -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - bg-space >=0.5.0
    - click
    - meshio
    - numpy
    - pandas
    - python >={{ python_min }}
    - requests
    - rich
    - tifffile
    - tqdm >=4.46.1
    - treelib

test:
  imports:
    - bg_atlasapi
  commands:
    - pip list
    - pip check
    - brainglobe --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/brainglobe/bg-atlasapi
  license: BSD-3-Clause
  license_file: gh_archive/LICENSE
  summary: A lightweight python module to interact with atlases for systems neuroscience

extra:
  recipe-maintainers:
    - conda-forge/napari
    - vigji
